[package]
name = "kiri-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
deku = { version = "0.12", default-features = false, features = ["alloc"] }
cobs = { version = "0.1.4" }

bitvec = { version = "0.22.1", default-features = false, features = ["alloc"] }
heapless = "0.7"

crc = "2.1"