[package]
name = "kiri-csma"
version = "0.1.0"
edition = "2021"

[dependencies]
nb = "1.0"
rand = { version = "0.8", default-features = false }
heapless = "0.7"

kiri-protocol = { path = "../protocol" }