[package]
name = "kiri-simulation"
version = "0.1.0"
edition = "2021"

[dependencies]
pretty_env_logger = "0.4"
log = "0.4"

nb = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

rand = "0.8"

kiri-protocol = { path = "../protocol" }
kiri-csma = { path = "../csma" }